name: Build release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create GitHub release
      run: gh release create $GITHUB_REF_NAME
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    name: Cargo build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features

    - name: Create tarball
      run: |
        outdir="./target"
        staging="$(basename ${{ github.repository }})-$GITHUB_REF_NAME"
        staging_archive="$staging.tar.gz"
        staging_archive_sum="$staging_archive.sha256"
        mkdir -p "$staging"

        cp README.md "$staging"
        cp "$outdir"/*/release/* "$staging"
        tar czf "$staging_archive" "$staging"
        shasum -a 256 "$staging_archive" "$staging_archive_sum"

        echo "ASSET=$staging_archive" >> $GITHUB_ENV
        echo "ASSET_SUM=$staging_archive_sum" >> $GITHUB_ENV

    - name: Upload to GitHub release
      run: gh release upload $GITHUB_REF_NAME ${{ env.ASSET }} ${{ env.ASSET_SUM }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
